### ISSUE TITLE
Collision AddEntityInDico

### ISSUE THREAD

**Issue by bnjMichel** [MatthieuMEZIL/waqs#12]
Could you change the key of the dictionary ClientEntitySetExtensions.AddEntityInDico method, the key is the GetHashCode () of the entity, the use of this key generates collisions, same key for different entities.
I suggest you use a uniqueidentifier.
Benjamin MICHEL

http://blogs.msdn.com/b/ericlippert/archive/2010/03/22/socks-birthdays-and-hash-collisions.aspx

**Comment by MatthieuMEZIL** [comment]
Fixed https://github.com/MatthieuMEZIL/waqs/commit/7597175aa1d99ec0a9fe76137ff5200cc3421683#diff-b871641bfb0de5dcbed208ce2b913aae
