### ISSUE TITLE
Add AddRange and AttachRange methods

### ISSUE THREAD

**Issue by bnjMichel** [MatthieuMEZIL/waqs#15]
Add AddRange and AttachRange methods on TrackableCollection
public void AddRange(
	IEnumerable<T> collection
)

public void AttachRange(
	IEnumerable<T> collection
)

Thanks
Benjamin MICHEL

**Comment by MatthieuMEZIL** [comment]
Done (https://github.com/MatthieuMEZIL/waqs/commit/61ab828b6585b1f2ebea06275fc69006f343d769)
